"""init schema

Revision ID: 82fe3d86938a
Revises: 
Create Date: 2026-05-13 11:31:23.756404

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82fe3d86938a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('polymarket_id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_tracked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_is_tracked'), 'events', ['is_tracked'], unique=False)
    op.create_index(op.f('ix_events_polymarket_id'), 'events', ['polymarket_id'], unique=True)
    op.create_table('llm_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('anthropic', 'openai', 'google', 'openrouter', name='llm_provider'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('model_id_at_provider', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_models_slug'), 'llm_models', ['slug'], unique=True)
    op.create_table('markets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('polymarket_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_outcome', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_event_id'), 'markets', ['event_id'], unique=False)
    op.create_index(op.f('ix_markets_is_resolved'), 'markets', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_markets_polymarket_id'), 'markets', ['polymarket_id'], unique=True)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('llm_model_id', sa.UUID(), nullable=False),
    sa.Column('predicted_probability_yes', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'llm_model_id', name='uq_prediction_market_model')
    )
    op.create_index(op.f('ix_predictions_llm_model_id'), 'predictions', ['llm_model_id'], unique=False)
    op.create_index(op.f('ix_predictions_market_id'), 'predictions', ['market_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=False),
    sa.Column('log_loss', sa.Float(), nullable=False),
    sa.Column('pnl_demo_usd', sa.Float(), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_prediction_id'), 'scores', ['prediction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_prediction_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_predictions_market_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_llm_model_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_markets_polymarket_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_is_resolved'), table_name='markets')
    op.drop_index(op.f('ix_markets_event_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_llm_models_slug'), table_name='llm_models')
    op.drop_table('llm_models')
    op.drop_index(op.f('ix_events_polymarket_id'), table_name='events')
    op.drop_index(op.f('ix_events_is_tracked'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
